
--CREATING USERS FOR GIVING THEM ROLES 
CREATE LOGIN Hamza WITH PASSWORD = '123';
CREATE USER Hamza FOR LOGIN Hamza;

CREATE LOGIN Khalid WITH PASSWORD = '456';
CREATE USER Khalid FOR LOGIN Khalid;

CREATE LOGIN Musa WITH PASSWORD = '789';
CREATE USER Musa FOR LOGIN Musa;


--CREATING ROLES
CREATE ROLE ManagerRole;

CREATE ROLE Property_role;

CREATE ROLE Leasing_role;

-- GIVING THE ROLES FOR USERS THAT I'VE CREATED BEFORE 
ALTER ROLE ManagerRole ADD MEMBER Hamza;

ALTER ROLE Property_role ADD MEMBER Musa;

ALTER ROLE Leasing_role ADD MEMBER Khalid;

-- GRANTING PRIVILEGES FOR ROLES 

--THESE PRIVILEGS FOR MANAGER AND WHO RESPONSILBE FOR TABLES THAT CONNECTED TO PROPERTY TABLE AND PROPERTY TABLE 
GRANT SELECT, INSERT, UPDATE, DELETE ON Property_manager TO ManagerRole, Property_role;
GRANT EXECUTE ON SCHEMA::dbo TO ManagerRole, Property_role;

GRANT SELECT, INSERT, UPDATE, DELETE ON Property TO ManagerRole, Property_role;
GRANT EXECUTE ON SCHEMA::dbo TO ManagerRole, Property_role;

GRANT SELECT, INSERT, UPDATE, DELETE ON Maintenance TO ManagerRole, Property_role;
GRANT EXECUTE ON SCHEMA::dbo TO ManagerRole, Property_role;

--THESE PRIVILEGS FOR MANAGER AND WHO RESPONSILBE FOR TABLES THAT CONNECTED TO LEASING_INFO TABLE AND LEASING_INFO TABLE 
GRANT SELECT, INSERT, UPDATE, DELETE ON Payment TO ManagerRole, Leasing_role;
GRANT EXECUTE ON SCHEMA::dbo TO ManagerRole, Leasing_role;

GRANT SELECT, INSERT, UPDATE, DELETE ON Tenant TO ManagerRole, Leasing_role;
GRANT EXECUTE ON SCHEMA::dbo TO ManagerRole, Leasing_role;

GRANT SELECT, INSERT, UPDATE, DELETE ON Leasing_info TO ManagerRole, Leasing_role;
GRANT EXECUTE ON SCHEMA::dbo TO ManagerRole, Leasing_role;

-- THIS PRIVILEGE FOR JUST Is_avaliable_for_rent COLUMN IN PROPERTY TABLE 
GRANT SELECT, UPDATE (Is_avaliable_for_rent) ON Property TO  Leasing_role;
GRANT EXECUTE ON SCHEMA::dbo TO Leasing_role;